# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ddev < Formula
  desc "DDEV"
  homepage "https://github.com/ddev/ddev"
  version "1.25.1"
  license "Apache 2"

  depends_on "mkcert"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ddev/ddev/releases/download/v1.25.1/ddev_macos-amd64.v1.25.1.tar.gz"
      sha256 "2ce471ce5a7f433fb454890e19827ae9deafed79d2ffaee52a40182c328ff144"

      define_method(:install) do
        if build.head?
            system "sh", "-c", "git fetch --unshallow >/dev/null 2>&1" if File.exist?("#{HOMEBREW_REPOSITORY}/.git/shallow")
            system "sh", "-c", "git fetch --tags -f >/dev/null 2>&1"
            os = OS.mac? ? "darwin" : "linux"
            arch = Hardware::CPU.arm? ? "arm64" : "amd64"
            system "mkdir", "-p", "#{bin}"
            system "make", "build", "completions"
            system "cp", ".gotmp/bin/" + os + "_" + arch + "/ddev", "#{bin}/ddev"
            system "cp", ".gotmp/bin/" + os + "_" + arch + "/ddev-hostname", "#{bin}/ddev-hostname"
            bash_completion.install ".gotmp/bin/completions/ddev_bash_completion.sh" => "ddev"
            zsh_completion.install ".gotmp/bin/completions/ddev_zsh_completion.sh" => "_ddev"
            fish_completion.install ".gotmp/bin/completions/ddev_fish_completion.sh" => "ddev.fish"
        else
            bin.install "ddev"
            bin.install "ddev-hostname"
            bash_completion.install "ddev_bash_completion.sh" => "ddev"
            zsh_completion.install "ddev_zsh_completion.sh" => "_ddev"
            fish_completion.install "ddev_fish_completion.sh" => "ddev.fish"
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ddev/ddev/releases/download/v1.25.1/ddev_macos-arm64.v1.25.1.tar.gz"
      sha256 "7d0dbe5edb700543fc48f579404bf14672e6d5958ef98751ff35e2f3ad8dd8f6"

      define_method(:install) do
        if build.head?
            system "sh", "-c", "git fetch --unshallow >/dev/null 2>&1" if File.exist?("#{HOMEBREW_REPOSITORY}/.git/shallow")
            system "sh", "-c", "git fetch --tags -f >/dev/null 2>&1"
            os = OS.mac? ? "darwin" : "linux"
            arch = Hardware::CPU.arm? ? "arm64" : "amd64"
            system "mkdir", "-p", "#{bin}"
            system "make", "build", "completions"
            system "cp", ".gotmp/bin/" + os + "_" + arch + "/ddev", "#{bin}/ddev"
            system "cp", ".gotmp/bin/" + os + "_" + arch + "/ddev-hostname", "#{bin}/ddev-hostname"
            bash_completion.install ".gotmp/bin/completions/ddev_bash_completion.sh" => "ddev"
            zsh_completion.install ".gotmp/bin/completions/ddev_zsh_completion.sh" => "_ddev"
            fish_completion.install ".gotmp/bin/completions/ddev_fish_completion.sh" => "ddev.fish"
        else
            bin.install "ddev"
            bin.install "ddev-hostname"
            bash_completion.install "ddev_bash_completion.sh" => "ddev"
            zsh_completion.install "ddev_zsh_completion.sh" => "_ddev"
            fish_completion.install "ddev_fish_completion.sh" => "ddev.fish"
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ddev/ddev/releases/download/v1.25.1/ddev_linux-amd64.v1.25.1.tar.gz"
      sha256 "7209de6c9aef9125e2bbe909b013f24c42cee55423da07f75f243b166deba741"
      define_method(:install) do
        if build.head?
            system "sh", "-c", "git fetch --unshallow >/dev/null 2>&1" if File.exist?("#{HOMEBREW_REPOSITORY}/.git/shallow")
            system "sh", "-c", "git fetch --tags -f >/dev/null 2>&1"
            os = OS.mac? ? "darwin" : "linux"
            arch = Hardware::CPU.arm? ? "arm64" : "amd64"
            system "mkdir", "-p", "#{bin}"
            system "make", "build", "completions"
            system "cp", ".gotmp/bin/" + os + "_" + arch + "/ddev", "#{bin}/ddev"
            system "cp", ".gotmp/bin/" + os + "_" + arch + "/ddev-hostname", "#{bin}/ddev-hostname"
            bash_completion.install ".gotmp/bin/completions/ddev_bash_completion.sh" => "ddev"
            zsh_completion.install ".gotmp/bin/completions/ddev_zsh_completion.sh" => "_ddev"
            fish_completion.install ".gotmp/bin/completions/ddev_fish_completion.sh" => "ddev.fish"
        else
            bin.install "ddev"
            bin.install "ddev-hostname"
            bash_completion.install "ddev_bash_completion.sh" => "ddev"
            zsh_completion.install "ddev_zsh_completion.sh" => "_ddev"
            fish_completion.install "ddev_fish_completion.sh" => "ddev.fish"
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ddev/ddev/releases/download/v1.25.1/ddev_linux-arm64.v1.25.1.tar.gz"
      sha256 "fb893c639296e343115d42355306cf221c7a7807aa55d1903f1433aae2c7d5cc"
      define_method(:install) do
        if build.head?
            system "sh", "-c", "git fetch --unshallow >/dev/null 2>&1" if File.exist?("#{HOMEBREW_REPOSITORY}/.git/shallow")
            system "sh", "-c", "git fetch --tags -f >/dev/null 2>&1"
            os = OS.mac? ? "darwin" : "linux"
            arch = Hardware::CPU.arm? ? "arm64" : "amd64"
            system "mkdir", "-p", "#{bin}"
            system "make", "build", "completions"
            system "cp", ".gotmp/bin/" + os + "_" + arch + "/ddev", "#{bin}/ddev"
            system "cp", ".gotmp/bin/" + os + "_" + arch + "/ddev-hostname", "#{bin}/ddev-hostname"
            bash_completion.install ".gotmp/bin/completions/ddev_bash_completion.sh" => "ddev"
            zsh_completion.install ".gotmp/bin/completions/ddev_zsh_completion.sh" => "_ddev"
            fish_completion.install ".gotmp/bin/completions/ddev_fish_completion.sh" => "ddev.fish"
        else
            bin.install "ddev"
            bin.install "ddev-hostname"
            bash_completion.install "ddev_bash_completion.sh" => "ddev"
            zsh_completion.install "ddev_zsh_completion.sh" => "_ddev"
            fish_completion.install "ddev_fish_completion.sh" => "ddev.fish"
        end
      end
    end
  end

  head do
    url "https://github.com/ddev/ddev.git", branch: "main"
    depends_on "go" => :build
    depends_on "make" => :build
  end
  # fail fast if tapped under the old drud or rfay names
  def initialize(*args, **kwargs)
    super(*args, **kwargs)
    if ["drud/homebrew-ddev", "rfay/homebrew-ddev"].include?(tap&.full_name)
      odie <<~EOS
        ERROR: your homebrew tap is the ancient #{tap.full_name},
        but that repository has moved.
        Please run:
          rm -rf "$(brew --repo #{tap.full_name})"
          brew uninstall -f ddev
          brew install ddev/ddev/ddev
      EOS
    end
  end

  test do
    system "#{bin}/ddev --version"
  end
end
